// <auto-generated />
using GlobalTax.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalTax.Persistence.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    [Migration("20250822090153_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalTax.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "US",
                            CountryName = "The United States of America",
                            Currency = "USD"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "VN",
                            CountryName = "Viet Nam",
                            Currency = "VND"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "AU",
                            CountryName = "Australia",
                            Currency = "AUD"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "CA",
                            CountryName = "Canada",
                            Currency = "CAD"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "TH",
                            CountryName = "Thailand",
                            Currency = "THB"
                        });
                });

            modelBuilder.Entity("GlobalTax.Domain.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TaxBracketJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxBrackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "US",
                            TaxBracketJson = "[{\"Level\":1,\"Limit\":11000,\"Rate\":0.10},{\"Level\":2,\"Limit\":44725,\"Rate\":0.12},{\"Level\":3,\"Limit\":95375,\"Rate\":0.22},{\"Level\":4,\"Limit\":182100,\"Rate\":0.24},{\"Level\":5,\"Limit\":231250,\"Rate\":0.32},{\"Level\":6,\"Limit\":578125,\"Rate\":0.35},{\"Level\":7,\"Limit\":999999999999999.99,\"Rate\":0.37}]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
